# Используем официальный образ PostgreSQL
FROM postgres:latest

# Устанавливаем переменные среды для автоматического создания пользователя и базы данных
ENV POSTGRES_USER=test
ENV POSTGRES_PASSWORD=test
ENV POSTGRES_DB=test

# Открываем порт 5432
EXPOSE 5432
